
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"


  my-postgres:
    image: postgres:15
    container_name: nats_postgres_assignment
    environment:
      POSTGRES_DB: natsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - nats-network

  nats-service:
    # directory that contains your Dockerfile
    build: .
    container_name: nats_service
    ports:
      - "8081:8081"  # Adjust if needed
    networks:
      - nats-network
    depends_on:
      - my-postgres

  nats-subscriber-app:
    build: .
    container_name: nats_subscriber_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/natsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - nats-network
    depends_on:
      - nats-service

networks:
  nats-network:
    driver: bridge
